package webcrawler;

import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import static java.lang.System.out;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

import webcrawler.LinkCollector;

/**
 *
 * @author eimantas
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.setVisible(true);
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.setResizable(false);
        this.setTitle("WEB crawler – Beta version");
        this.setStatusLabel("Ready");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        statusPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        URLfield = new javax.swing.JTextField();
        keywordField = new javax.swing.JTextField();
        linksToCrawlField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        outputField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bodySearchButton = new javax.swing.JButton();
        titleSearchButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        statusPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        statusLabel.setText("");

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(statusLabel))
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(statusLabel))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        URLfield.setText("");
        URLfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        keywordField.setText("");
        keywordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        linksToCrawlField.setText("");
        linksToCrawlField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Number of links to crawl");

        jLabel2.setText("Phrase to look for");

        jLabel3.setText("URL, e.g. www.15min.lt");

        outputField.setText("");
        outputField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Enter a filename to store output");

        bodySearchButton.setText("Text Search");

        titleSearchButton.setText("Search by title");

        resetButton.setText("Reset");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(outputField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(keywordField)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(URLfield)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(132, 132, 132)
                                    .addComponent(linksToCrawlField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(titleSearchButton)
                            .addGap(15, 15, 15)
                            .addComponent(bodySearchButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resetButton))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(URLfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keywordField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linksToCrawlField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bodySearchButton)
                    .addComponent(titleSearchButton)
                    .addComponent(resetButton))
                .addGap(69, 69, 69))
        );

        bodySearchButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                setStatusLabel("Running");
                refreshStatusPanel();
                String link = WebCrawler.gui.getURLField();
                if( !link.contains("https://")){
                    link = "https://"+link;
                }
                String keyword = WebCrawler.gui.getKeywordField();

                if( !keyword.isEmpty() && getNoLinks() >= 0 ){
                    WebCrawler.linkCollector.setPhrase(keyword);
                    WebCrawler.linkCollector.setLinksToCrawl(getNoLinks());
                    if(!getOutputField().isEmpty()){
                        WebCrawler.linkCollector.setOutputFile(getOutputField());
                    }
                    if( link.toLowerCase().contains("wikipedia.org")){
                        WebCrawler.linkCollector.setWikiLang(link);
                        WebCrawler.linkCollector.scrapWiki(link);
                    } else {
                        WebCrawler.linkCollector.searchByBody(link);
                    }
                    WebCrawler.linkCollector.writeToFile();
                    WebCrawler.linkCollector.openFile();
                } else if( keyword.isEmpty()){
                    out.println("Enter a keyword!");
                } else if( getNoLinks() < 0 ){
                    out.println("Number of links to crawl : bad data type! Enter integer value!");
                }
                setStatusLabel("Done");
                refreshStatusPanel();
            }
        }
    );
    titleSearchButton.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            String link = getURLField();
            if( !link.isEmpty() && !link.contains("https://")){
                link = "https://"+link;
            }
            String keyword = getKeywordField();
            if( !getOutputField().isEmpty() ){
                //WebCrawler.linkCollector.setOutputFile(getOutputField());
                WebCrawler.linkCollector.setOutputFile(getOutputField());
            }
            if( getNoLinks() >= 0 ){
                WebCrawler.linkCollector.setLinksToCrawl(getNoLinks());
            } else {
                out.println("Number of links to crawl : bad data type! Enter integer value!");
            }
            if( !keyword.isEmpty()  ){
                WebCrawler.linkCollector.setPhrase(keyword);
                WebCrawler.linkCollector.searchByTitle(link);
            }
            WebCrawler.linkCollector.writeToFile();
            WebCrawler.linkCollector.openFile();
            setStatusLabel("Done");
        }
    }
    );
    resetButton.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            int dialogResult = JOptionPane.showConfirmDialog (null, "All gatheted information will be lost. Are you sure about this action?","Warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                WebCrawler.linkCollector.resetFields();
            } else {

            }
        }
    }
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void wiki(String link){
        WebCrawler.linkCollector.scrapWiki(link);
    }
    /**
     * @param args the command line arguments
     */
    
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI().setVisible(true);
//            }
//        });
//    }

    public String getURLField(){
        return this.URLfield.getText();
    }
    public String getOutputField(){
        return outputField.getText();
    }
    public String getKeywordField(){
        return this.keywordField.getText();
    }
    public int getNoLinks(){
        if( this.linksToCrawlField.getText().matches("[0-9]+") ){
            return Integer.valueOf(this.linksToCrawlField.getText());
        } else {
            return -1;
        }
    }
    public void cleanNoLinks(){
        this.linksToCrawlField.setText("");
    }
    public void cleanKeywordField(){
        this.keywordField.setText("");
    }
    public void cleanOutputField(){
        this.outputField.setText("");
    }
    public void cleanURLField(){
        this.URLfield.setText("");
    }
    public void setStatusLabel(String status){
        this.statusLabel.setText(status);
        statusLabel.repaint();
    }
    public void refreshStatusPanel(){
        statusPanel.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField URLfield;
    private javax.swing.JButton bodySearchButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField keywordField;
    private javax.swing.JTextField linksToCrawlField;
    private javax.swing.JTextField outputField;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JButton titleSearchButton;
    // End of variables declaration//GEN-END:variables
}
